import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "../globals.css";
import { Navbar } from "@/components/navbar";
import { createServerSupabaseClient } from "@/lib/supabase/server";
import { locales } from "@/features/i18n/config";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return locales.map((locale) => ({ locale }));
}

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;
  const supabase = await createServerSupabaseClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  return (
    <html lang={locale}>
      <body className={`${outfit.variable} antialiased`}>
        <Navbar user={user} />
        {children}
      </body>
    </html>
  );
}
